### ISSUE TITLE
gsldefs.vcxproj not found

### ISSUE THREAD

**Issue by UnitedMarsupials** [BrianGladman/gsl#1]
Hello!

I've setup a Jenkins-project to checkout GSL from your repository and build it. The build has the following steps:

- `msbuild` using `build.vc/gsl.dll.sln` with target `/t:gslhdrs`
- `msbuild` using `build.vc/gsl.dll.sln` with default target(s)
- `msbuild` using `build.vc/test.gsl.dll.sln` (default target(s))

The last such build, attempted in January 2020 (11 months ago) was against 77f01ef241a344b1c11199e68e82b1a44e62d221, and successful.

Today I attempted to refresh our library and invoked the build against the 28b629c9e1a61b41ef3cb6e9e0747e41ea7b939e. This attempt failed at the second step above:

> ...
> 12:55:39  "D:\CI\.jenkins\workspace\GSL\build.vc\gsl.dll.sln" (default target) (1) ->
> 12:55:39  (Build target) ->
> 12:55:39    D:\CI\.jenkins\workspace\GSL\build.vc\gsl.dll.sln.metaproj : error MSB3202: **The project file "D:\CI\.jenkins\workspace\GSL\build.vc\gsldefs\gsldefs.vcxproj" was not found**. [D:\CI\.jenkins\workspace\GSL\build.vc\gsl.dll.sln]
> 12:55:39
> 12:55:39      507 Warning(s)
> 12:55:39      1 Error(s)

[Full log](https://github.com/BrianGladman/gsl/files/5740332/GSL-build.log) attached...

The `gsldefs.vcxproj` was removed by the commit, but something continues to refer to it...

**Comment by BrianGladman** [comment]
My apologies for the omission of the build file for gsldefs.c, which I have put back.  I have had to make a small change to this file which I cannot test directly so it might not  work.   If it fails please let me know here.

**Comment by UnitedMarsupials** [comment]
Thank you for the prompt response. The build of 4795f82d8079d0d166ae8c3b3fb06a02ec88d584 completed successfully.

I just realized, that although the tests are _built_, they are not _run_ by my process... How would I invoke them -- and should I expect them all to complete successfully?

**Comment by BrianGladman** [comment]
The build of each test also runs the test so errors will show up during the build process if any test fails.  They can also be run manually using the python files named run-tests.py in either the dlltest or libtest sub-directories within in the build.vc directory.  This is sometimes necessary if the build fails because Visual Studio tries to run too many parallel build processes.

**Comment by UnitedMarsupials** [comment]
> The build of each test also runs the test so errors will show up during the build process if any test fails. 

Ah, cool, then I've been running them all along. Thanks. You can close this (very first!) ticket -- and keep the average ticket-closing time under 24 hours :-)
