### ISSUE TITLE
Visual Studio 2017 Build Error

### ISSUE THREAD

**Issue by mancoast** [BrianGladman/gsl#10]
Command line error D8016: '/O2' and '/RTC1' command-line options are incompatible [C:\projects\gsl-msvc\build.vc\cblasdll\cblasdll.vcxproj]
![image](https://user-images.githubusercontent.com/7040493/31189925-98491006-a907-11e7-8a40-ee823fd51dcf.png)

**Comment by BrianGladman** [comment]
Hi, I am a bit puzzled by this as I don't have the GSL build set with both /O2 and /RTC1 enabled.   Have you had to change this in order to use Appveyor?

**Comment by mancoast** [comment]
Greetings @BrianGladman,
This error occurs on my local machines, also the scenario is replicated to appveyor.
I have tried compilation on three separate local machines and the debug builds produce the D8016 error.
build logs available [here ](https://ci.appveyor.com/project/mancoast/gsl-msvc/build/1.0.1.0.0.7.16-master)

The solution works flawlessly for release builds, only occurs for Debug.
Looks like we also need to modify debug x64 in the vcxproj

**Comment by BrianGladman** [comment]
OK, I think I know what to do. I introduced property sheets to simplify the build configuration but I think some of the property sheets for debug builds need some changes. I will take a look at this now.

**Comment by BrianGladman** [comment]
I have pushed a correction to the property sheets that I hope will fix the issue.

**Comment by mancoast** [comment]
9a938f0 resolved
