### ISSUE TITLE
enable appveyor githooks for BrianGladman/gsl repo

### ISSUE THREAD

**Issue by mancoast** [BrianGladman/gsl#12]
Greetings,

Please enable the windows continuous integration via Githooks.
This requires logging into Appveyor using your Github.
Then select the BrianGladman/gsl repo with the slider to enable continuous integration.
![image](https://user-images.githubusercontent.com/7040493/31190554-6b32d0fa-a909-11e7-8a03-02ca06cbefdb.png)

![image](https://user-images.githubusercontent.com/7040493/31190433-0b938018-a909-11e7-8c85-a9cae6edf652.png)

Thanks!
coast

**Comment by BrianGladman** [comment]
So I have to create a new account on Appveyor?

I have tried this and for some reason it makes reference to YASM in the signup dialogue - this leaves me a bit worried as YASM is not my project (I just shadow Peter Johnson's YASM project here).

**Comment by mancoast** [comment]
essentially, you can use a github oath token to login to appveyor.
I do not have a separate account for appveyor, I just use my github account.

There is a way to completely avoid signing up if you login with Github.

After you get the system rolling, it add build status indicators next to each commit:
![image](https://user-images.githubusercontent.com/7040493/31200979-f9a56016-a92a-11e7-9d21-51e417ffaf91.png)

**Comment by BrianGladman** [comment]
OK, I have now managed to do this and I can see Appveyor running a build.  Nothing has tuned up here yet but I imagine that this might take some time.

**Comment by mancoast** [comment]
Nicely done! I can confirm its functional as the appveyor is building pull request #11 👍
![image](https://user-images.githubusercontent.com/7040493/31203180-ec897530-a933-11e7-9fc4-36af01d07e96.png)
