### ISSUE TITLE
Impossible to compile DLL

### ISSUE THREAD

**Issue by Scipius81** [BrianGladman/gsl#20]
Hi Brian,
I'm trying to compile gsl.dll, but the compiling process stops with the following error:

`1>LINK : fatal error LNK1104: cannot open file 'C:\Users\XXX\Downloads\gsl-master\gsl-master\build.vc\..\dll\Win32\Debug\cblas.lib'`

In the destiantion folder there is no cblas.lib file, while cblas.dll is present. 

It seems to me that the cblasdll project is not set to produce cblas.lib file, or gsldll search for cblas.lib instead of cblas.dll

Is there a way to solve it?
Thanks for your efforts!
Bests

**Comment by Scipius81** [comment]
Hi Brian,
I've an update: 
1) I flag "Yes" on the "Ignore imput Library" option on the cblasddl project
2) I change the "Additional Dependencies" of gsldll project from "cbals.lib" to "cblas.dll".

The error I obtain now is 
`gsl-master\gsl-master\build.vc\..\dll\x64\Release\cblas.dll : fatal error LNK1107: invalid or corrupt file: cannot read at 0x340`

Can you help me? What's wrong?
Bests

**Comment by BrianGladman** [comment]
HI, I can see the build error that you are experiencing and I will see what I can do to fix it.  I am sorry that I cannot offer you an immediate solution.

**Comment by BrianGladman** [comment]
I reacted to your second comment by setting the additional dependencies to cblas.dll as you did and got the same result.  But this is incorrect.   When cblas.dll is built it should produce three components cbllas.dll, cbls.lib and cblas.exp.   When gsl.dll is built it links to cblas.lib and I have checked that this works for me.  So we need to understand why cblas.lib is not being produced when you build cblas.dll.    I can only suggest that you clean the cblas.dll project, rebuild it and double check that cblas.lib is not being produced.   If it isn't its hard to know what is going wrong.

**Comment by Scipius81** [comment]
I finally obtain the DLL!
I just need to run the two exe files gslhdrs.exe and gsldefs.exe BEFORE compiling cblasdll and gsl.dll.
Bests

**Comment by BrianGladman** [comment]
I can now see that you did not read the build instructions before trying to build the library!   In fact you only need to run one of gsldefs.exe and gslhdrs.exe, not both, before building the two main libraries (CBLAS and GSL).   The use of gslhdrs.exe is preferable as it offers the potential of better performance and this is the approach you got by running both.  I pleased that you got there in the end.

**Comment by Scipius81** [comment]
Yes, thank you for your great work!
Anyway, where can I find the build instructions?

**Comment by BrianGladman** [comment]
The build process is described in the file gsl.reade.txt in the build.vc directory.
