### ISSUE TITLE
error C2071: 'matrix_ptr': illegal storage class and  error C2071: 'rhs_ptr': illegal storage class

### ISSUE THREAD

**Issue by ethandylan** [BrianGladman/gsl#21]
HI, everyone, when i compile gsl with visual studio 2019, i meet above errors.  
Finally I fix this error by removing the  GSL_FUN prefix

**Comment by Suthiro** [comment]
I've got the same bug compiling with VS 2017. Removing the ``` GSL_FUN``` does the trick, but I wonder what the consequences are.

**Comment by BrianGladman** [comment]
Yes, This is a bug in my code for generating the modified GSL headers.   

Removing the GSL_FUN symbols from these two lines is the right solution until I can find time to correct the header generation code.
