### ISSUE TITLE
Multiple compilation failures in hermite.c

### ISSUE THREAD

**Issue by anates** [BrianGladman/gsl#3]
When compiling with VC15, I get multiple errors in the file "hermite.c":
`1>..\..\specfunc\hermite.c(88): error C2059: Syntax error: "/"
1>..\..\specfunc\hermite.c(93): error C2059: Syntax error: "else"
1>..\..\specfunc\hermite.c(97): error C2059: Syntax error: "else"
1>..\..\specfunc\hermite.c(101): error C2059: Syntax error: "}"
1>..\..\specfunc\hermite.c(106): error C2059: Syntax error: "return"
1>..\..\specfunc\hermite.c(108): error C2059: Syntax error: "}"
1>..\..\specfunc\hermite.c(197): error C2059: Syntax error: "}"
1>..\..\specfunc\hermite.c(244): error C2143: Syntax error: Missing")" before "*"
1>..\..\specfunc\hermite.c(244): error C2081: "gsl_sf_result": Name in der formalen Parameterliste ist ungültig
1>..\..\specfunc\hermite.c(244): error C2143: Syntax error: Missing"{" before "*"
1>..\..\specfunc\hermite.c(244): error C2059: Syntax error: ")"
1>..\..\specfunc\hermite.c(247): error C2054: Nach "result" muss "(" folgen
1>..\..\specfunc\hermite.c(260): warning C4013: "EVAL_RESULT" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(260): warning C4013: "gsl_sf_hermite_prob_e" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(264): error C2143: Syntax error: Missing")" before "*"
1>..\..\specfunc\hermite.c(264): error C2081: "gsl_sf_result": Name in der formalen Parameterliste ist ungültig
1>..\..\specfunc\hermite.c(264): error C2143: Syntax error: Missing"{" before "*"
1>..\..\specfunc\hermite.c(264): error C2059: Syntax error: ")"
1>..\..\specfunc\hermite.c(267): error C2054: Nach "result" muss "(" folgen
1>..\..\specfunc\hermite.c(292): warning C4013: "EVAL_RESULT" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(292): warning C4013: "gsl_sf_hermite_prob_der_e" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(296): error C2143: Syntax error: Missing")" before "*"
1>..\..\specfunc\hermite.c(296): error C2081: "gsl_sf_result": Name in der formalen Parameterliste ist ungültig
1>..\..\specfunc\hermite.c(296): error C2143: Syntax error: Missing"{" before "*"
1>..\..\specfunc\hermite.c(296): error C2059: Syntax error: ")"
1>..\..\specfunc\hermite.c(299): error C2054: Nach "result" muss "(" folgen
1>..\..\specfunc\hermite.c(471): warning C4013: "EVAL_RESULT" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(471): warning C4013: "gsl_sf_hermite_phys_e" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(475): error C2143: Syntax error: Missing")" before "*"
1>..\..\specfunc\hermite.c(475): error C2081: "gsl_sf_result": Name in der formalen Parameterliste ist ungültig
1>..\..\specfunc\hermite.c(475): error C2143: Syntax error: Missing"{" before "*"
1>..\..\specfunc\hermite.c(475): error C2059: Syntax error: ")"
1>..\..\specfunc\hermite.c(478): error C2054: Nach "result" muss "(" folgen
1>..\..\specfunc\hermite.c(504): warning C4013: "EVAL_RESULT" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(504): warning C4013: "gsl_sf_hermite_phys_der_e" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(508): error C2143: Syntax error: Missing")" before "*"
1>..\..\specfunc\hermite.c(508): error C2081: "gsl_sf_result": Name in der formalen Parameterliste ist ungültig
1>..\..\specfunc\hermite.c(508): error C2143: Syntax error: Missing"{" before "*"
1>..\..\specfunc\hermite.c(508): error C2059: Syntax error: ")"
1>..\..\specfunc\hermite.c(511): error C2054: Nach "result" muss "(" folgen
1>..\..\specfunc\hermite.c(668): warning C4013: "EVAL_RESULT" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(668): warning C4013: "gsl_sf_hermite_func_e" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(679): warning C4013: "GSL_ERROR" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(679): error C2065: "GSL_EDOM": undefined identifier
1>..\..\specfunc\hermite.c(683): error C2065: "GSL_SUCCESS": undefined identifier
1>..\..\specfunc\hermite.c(688): error C2065: "GSL_SUCCESS": undefined identifier
1>..\..\specfunc\hermite.c(706): warning C4013: "fmin" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(706): error C2065: "GSL_SQRT_DBL_MIN": undefined identifier
1>..\..\specfunc\hermite.c(706): warning C4013: "fmax" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(706): error C2065: "GSL_SQRT_DBL_MAX": undefined identifier
1>..\..\specfunc\hermite.c(713): error C2065: "GSL_SQRT_DBL_MIN": undefined identifier
1>..\..\specfunc\hermite.c(713): error C2065: "GSL_SQRT_DBL_MAX": undefined identifier
1>..\..\specfunc\hermite.c(720): warning C4013: "pow2" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(723): error C2065: "GSL_SUCCESS": undefined identifier
1>..\..\specfunc\hermite.c(737): warning C4013: "GSL_ERROR" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(737): error C2065: "GSL_EDOM": undefined identifier
1>..\..\specfunc\hermite.c(741): error C2065: "GSL_SUCCESS": undefined identifier
1>..\..\specfunc\hermite.c(748): error C2065: "GSL_SUCCESS": undefined identifier
1>..\..\specfunc\hermite.c(755): warning C4013: "gsl_sf_fact" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(756): error C2065: "GSL_SUCCESS": undefined identifier
1>..\..\specfunc\hermite.c(763): warning C4013: "gsl_sf_fact" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(765): error C2065: "GSL_SUCCESS": undefined identifier
1>..\..\specfunc\hermite.c(770): warning C4013: "gsl_sf_fact" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(787): warning C4013: "fmin" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(787): error C2065: "GSL_SQRT_DBL_MIN": undefined identifier
1>..\..\specfunc\hermite.c(787): warning C4013: "fmax" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(787): error C2065: "GSL_SQRT_DBL_MAX": undefined identifier
1>..\..\specfunc\hermite.c(794): error C2065: "GSL_SQRT_DBL_MIN": undefined identifier
1>..\..\specfunc\hermite.c(794): error C2065: "GSL_SQRT_DBL_MAX": undefined identifier
1>..\..\specfunc\hermite.c(801): warning C4013: "pow2" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(804): error C2065: "GSL_SUCCESS": undefined identifier
1>..\..\specfunc\hermite.c(817): warning C4013: "GSL_ERROR" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(817): error C2065: "GSL_EDOM": undefined identifier
1>..\..\specfunc\hermite.c(825): error C2065: "GSL_SUCCESS": undefined identifier
1>..\..\specfunc\hermite.c(834): error C2065: "GSL_SUCCESS": undefined identifier
1>..\..\specfunc\hermite.c(838): error C2065: "GSL_SUCCESS": undefined identifier
1>..\..\specfunc\hermite.c(843): error C2065: "GSL_SUCCESS": undefined identifier
1>..\..\specfunc\hermite.c(848): warning C4013: "GSL_MAX_INT" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(859): warning C4013: "GSL_MIN_INT" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(868): warning C4013: "fmin" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(868): error C2065: "GSL_SQRT_DBL_MIN": undefined identifier
1>..\..\specfunc\hermite.c(868): warning C4013: "fmax" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(868): error C2065: "GSL_SQRT_DBL_MAX": undefined identifier
1>..\..\specfunc\hermite.c(875): error C2065: "GSL_SQRT_DBL_MIN": undefined identifier
1>..\..\specfunc\hermite.c(875): error C2065: "GSL_SQRT_DBL_MAX": undefined identifier
1>..\..\specfunc\hermite.c(882): warning C4013: "pow2" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(891): error C2065: "GSL_SUCCESS": undefined identifier
1>..\..\specfunc\hermite.c(897): error C2143: Syntax error: Missing")" before "*"
1>..\..\specfunc\hermite.c(897): error C2081: "gsl_sf_result": Name in der formalen Parameterliste ist ungültig
1>..\..\specfunc\hermite.c(897): error C2143: Syntax error: Missing"{" before "*"
1>..\..\specfunc\hermite.c(897): error C2059: Syntax error: ")"
1>..\..\specfunc\hermite.c(900): error C2054: Nach "result" muss "(" folgen
1>..\..\specfunc\hermite.c(952): warning C4013: "EVAL_RESULT" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(952): warning C4013: "gsl_sf_hermite_prob_series_e" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(963): warning C4013: "GSL_ERROR" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(963): error C2065: "GSL_EDOM": undefined identifier
1>..\..\specfunc\hermite.c(967): error C2065: "GSL_SUCCESS": undefined identifier
1>..\..\specfunc\hermite.c(972): error C2065: "GSL_SUCCESS": undefined identifier
1>..\..\specfunc\hermite.c(990): warning C4013: "fmin" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(990): error C2065: "GSL_SQRT_DBL_MIN": undefined identifier
1>..\..\specfunc\hermite.c(990): warning C4013: "fmax" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(990): error C2065: "GSL_SQRT_DBL_MAX": undefined identifier
1>..\..\specfunc\hermite.c(997): error C2065: "GSL_SQRT_DBL_MIN": undefined identifier
1>..\..\specfunc\hermite.c(997): error C2065: "GSL_SQRT_DBL_MAX": undefined identifier
1>..\..\specfunc\hermite.c(1004): warning C4013: "pow2" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(1007): error C2065: "GSL_SUCCESS": undefined identifier
1>..\..\specfunc\hermite.c(1020): warning C4013: "GSL_ERROR" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(1020): error C2065: "GSL_EDOM": undefined identifier
1>..\..\specfunc\hermite.c(1024): error C2065: "GSL_SUCCESS": undefined identifier
1>..\..\specfunc\hermite.c(1031): error C2065: "GSL_SUCCESS": undefined identifier
1>..\..\specfunc\hermite.c(1039): warning C4013: "pow2" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(1039): warning C4013: "gsl_sf_fact" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(1040): error C2065: "GSL_SUCCESS": undefined identifier
1>..\..\specfunc\hermite.c(1048): warning C4013: "pow2" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(1048): warning C4013: "gsl_sf_fact" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(1050): error C2065: "GSL_SUCCESS": undefined identifier
1>..\..\specfunc\hermite.c(1056): warning C4013: "pow2" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(1056): warning C4013: "gsl_sf_fact" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(1073): warning C4013: "fmin" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(1073): error C2065: "GSL_SQRT_DBL_MIN": undefined identifier
1>..\..\specfunc\hermite.c(1073): warning C4013: "fmax" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(1073): error C2065: "GSL_SQRT_DBL_MAX": undefined identifier
1>..\..\specfunc\hermite.c(1080): error C2065: "GSL_SQRT_DBL_MIN": undefined identifier
1>..\..\specfunc\hermite.c(1080): error C2065: "GSL_SQRT_DBL_MAX": undefined identifier
1>..\..\specfunc\hermite.c(1090): error C2065: "GSL_SUCCESS": undefined identifier
1>..\..\specfunc\hermite.c(1103): warning C4013: "GSL_ERROR" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(1103): error C2065: "GSL_EDOM": undefined identifier
1>..\..\specfunc\hermite.c(1111): error C2065: "GSL_SUCCESS": undefined identifier
1>..\..\specfunc\hermite.c(1120): error C2065: "GSL_SUCCESS": undefined identifier
1>..\..\specfunc\hermite.c(1124): error C2065: "GSL_SUCCESS": undefined identifier
1>..\..\specfunc\hermite.c(1129): error C2065: "GSL_SUCCESS": undefined identifier
1>..\..\specfunc\hermite.c(1134): warning C4013: "GSL_MAX_INT" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(1145): warning C4013: "GSL_MIN_INT" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(1154): warning C4013: "fmin" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(1154): error C2065: "GSL_SQRT_DBL_MIN": undefined identifier
1>..\..\specfunc\hermite.c(1154): warning C4013: "fmax" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(1154): error C2065: "GSL_SQRT_DBL_MAX": undefined identifier
1>..\..\specfunc\hermite.c(1161): error C2065: "GSL_SQRT_DBL_MIN": undefined identifier
1>..\..\specfunc\hermite.c(1161): error C2065: "GSL_SQRT_DBL_MAX": undefined identifier
1>..\..\specfunc\hermite.c(1168): warning C4013: "pow2" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(1177): error C2065: "GSL_SUCCESS": undefined identifier
1>..\..\specfunc\hermite.c(1183): error C2143: Syntax error: Missing")" before "*"
1>..\..\specfunc\hermite.c(1183): error C2081: "gsl_sf_result": Name in der formalen Parameterliste ist ungültig
1>..\..\specfunc\hermite.c(1183): error C2143: Syntax error: Missing"{" before "*"
1>..\..\specfunc\hermite.c(1183): error C2059: Syntax error: ")"
1>..\..\specfunc\hermite.c(1186): error C2054: Nach "result" muss "(" folgen
1>..\..\specfunc\hermite.c(1238): warning C4013: "EVAL_RESULT" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(1238): warning C4013: "gsl_sf_hermite_phys_series_e" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(1250): warning C4013: "GSL_ERROR" undefined; Annahme: extern mit Rückgabetyp int
1>..\..\specfunc\hermite.c(1250): error C2065: "GSL_EDOM": undefined identifier
1>..\..\specfunc\hermite.c(1253): error C2065: "M_SQRTPI": undefined identifier
1>..\..\specfunc\hermite.c(1254): error C2065: "GSL_SUCCESS": undefined identifier`
How can I fix them?

**Comment by BrianGladman** [comment]
The sort of errors you are seeing suggests that some files in GSL have got corrupted in some way or have not been built correctly.  Did you build the gslhdrs or gsldefs before you tried to build cblaslib and gsllib?  I think it might be sensible to download and start again from scratch to see if the same problem recurs.

**Comment by anates** [comment]
Everything except gsllib works fine and can be compiled. Only hermite.c fails.

**Comment by BrianGladman** [comment]
I have just retested the build in Visual Studio 2015 and it is working fine for me.  I cannot think of any reason why only one file would fail to compile - have you checked that the file hasn't changed in some way since you downloaded it?.

**Comment by neffw** [comment]
Same for me on Visual Studio 2015 Update 3. The failure is cause by the following comments in hermite.c and hermite.h which confuse the parser:
```
hermite.h
//*----------------------------------------------------------------------*
//* (konradg(at)gmx.net)                                                 *
//*----------------------------------------------------------------------*

hermite.c
//*----------------------------------------------------------------------*
//* "The purpose of computing is insight, not numbers." - R.W. Hamming   *
//* Hermite polynomials, Hermite functions                               *
//* and their respective arbitrary derivatives                           *
//*----------------------------------------------------------------------*
```
Apparently the compiler does not like comments starting with `//*`.

**Comment by BrianGladman** [comment]
I have just tested the current build with Visual Studio 2015 Enterprise with Update 3 (14.0.25422.01) and hermite.c compiles  fine for me.  It does, however, require the C/C++ language extensions to be enabled - but, since this is how the build is set up, this should not cause the build to fail.   If you temporarily change '//*' in hermite.h and hermit.c to '// ' does the build then work?

**Comment by neffw** [comment]
No, Brian. I checked out commit 44c4987 for the Visual Studio 2015 solution files, opened build.vc/gsl.lib, pressed _Build Solution_ and got 102 Errors and 52 Warnings in hermite.c. After replacing `//*` by `//` in hermite.c and gsl_sf_hermite.h I got the [attached error messages](https://github.com/BrianGladman/gsl/files/981838/gsl-log.txt.txt). Since I was not keen on fixing illegal initializations I quit and used the NuGet installation packages.

Nonetheless I would prefer to use the Visual Studio Build Files. In view of the illegal initialization errors it makes sense that you say that C/C++ language extensions have to be enabled.

**Comment by BrianGladman** [comment]
Ah, now I understand why we are seeing different results.  Visual Studio 2015 can read Visual Studio 2017 solutions so you can check out from head, which will load fine in VS 2015.  All you then have to do is to change the toolset (in Configuration Properties|General) from v141 to v140 and you should get a successful build.

**Comment by neffw** [comment]
It is a bit clearer now. I checked out the latest commit, switched Target Platform Version back to _8.1_, Platform Toolset to _Visual Studio 2015 (v140)_ and opened solution _gsl.lib_. 

Rebuilding the solution with configuration _Debug_ produces a bunch of [errors and warnings](https://github.com/BrianGladman/gsl/files/999194/log.txt). The missing header files are found by building the solution repeatedly, but the illegal initializations remain.
```
Error	C2097	illegal initialization	gsllib	C:\Users\...\Documents\Visual Studio 2015\Projects\gsl\multifit_nlinear\trust.c	233	
Error	C2097	illegal initialization	gsllib	C:\Users\...\Documents\Visual Studio 2015\Projects\gsl\multifit_nlinear\trust.c	293	
Error	C2097	illegal initialization	gsllib	C:\Users\...\Documents\Visual Studio 2015\Projects\gsl\multifit_nlinear\trust.c	467	
```
However, the code compiles using configuration _Release_. I think solution configuration _Debug_ is misconfigured.

**Comment by BrianGladman** [comment]
I deliberately disable Microsoft language extensions when in Debug mode because GSL is supposed to build with a standard C compiler and this allows me to report code for which this isn't true.  However, I enable the extensions in Release mode because most users expect GSL to work 'out of the box' and are not concerned that this happens to require the Microsoft language extensions.   

I intend to add details about the need to select the Platform in the gslreadme file when I have time.   Thank you for your interest in the build.

**Comment by neffw** [comment]
Okay, I see. Thanks for the quick support and thank you for the great work.
