### ISSUE TITLE
Verify and Validate all known GSL tests

### ISSUE THREAD

**Issue by mancoast** [BrianGladman/gsl#7]
Greetings,

Prior to release of GSL 2.4, ode2 test fails.
As of release 2.4, there are new test failures.
REFERENCE:
https://lists.gnu.org/archive/html/help-gsl/2017-06/msg00031.html

We should wait to package the NUGET until these tests all pass.

Thanks,
coast

**Comment by BrianGladman** [comment]
Those failures are with mingw/GCC.  I have just run all the tests with MSVC and the only failure is ode2. I have spent a lot of time trying to find out why it fails but no luck I'm afraid.  Thanks for your work on NUGET.

**Comment by mancoast** [comment]
Greetings Brian,

I cannot execute the TestMatrix.exe or TestVector.exe binaries.
For my system, I see "HEAP CORRUPTION DETECTED".

![gsl_2 4_msvc_fail](https://user-images.githubusercontent.com/7040493/27395734-ccbb53de-567e-11e7-8cb5-a357c2c7e5c5.png)

Any thoughts?

Thanks,
coast

**Comment by BrianGladman** [comment]
That is odd.  I have just rebuilt the x64/release static and DLL libraries and the tests and I only see one test failure in ode2.   I have no idea what might be going on but I do remember that these two tests did cause problems in my older builds.

**Comment by BrianGladman** [comment]
If I read the reports correctly, these errors arise because the vector and matrix tests attempt to create a temporary file in the root directory and this will fail if the user's account doesn't have write access to this directory.  Since I am running on my own machine in an admin account, I have full access to C:\ so I don't see the error.   But anyone running in a user account won't have access to write to the root directory and will hence see a test failure.    It is easy to solve on Windows but we need a solution that makes sense on GCC/Linux as well.

**Comment by mancoast** [comment]
Thanks for resolving the tmp file stuff. 
Any pointers you can add to help my spinup on the ode2 logic?
I will take a look as we continue discussion.

**Comment by BrianGladman** [comment]
The ode2 failure is not a simple one and I would certainly appreciate some help in getting to the bottom of what is going on.   Here is what I know about it.   Firstly binaries built with Visual Studio 2012 (MSVC 11) work on both my nehalem and skylake machines.  Secondly, binaries built with Visual Studio 2015 and 2017 (MSVC 14) work on my nehalem system but fail on my skylake system.    It hence seems that the problem has something to do with how the compiler builds floating point operations.

**Comment by yangzaige00001** [comment]
I also gat problems when using odeiv2. I'm new with GSL and I have a question: is the .tar.gz file contains all the source code of the GSL library? For I can't find the implementation of some functions and classes in the folder odeiv2. I met linking error for the linker can't find their implementations. Thankyou :-)
ps: environment: MSVC12 ,GSL2.4, WIN7x64

**Comment by BrianGladman** [comment]
The gsl-2.4.tar.gz file should contain all the source code for the current version of GSL.   The distribution here also contains all the GSL source code so you could download in .zip format from here to check if anything is missing in the tar.gz file.

**Comment by yangzaige00001** [comment]
Thank you so much! With your suggestion, I find the reason. I used the search function in windows explorer incorrectly. If I want to search the content of every file. I should first add the current path to search index. Otherwise the search result is not comprehensive.
