### ISSUE TITLE
gsl/gsl_types.h

### ISSUE THREAD

**Issue by lbertolotti** [BrianGladman/gsl#8]
gsl-2.4, Windows 10 64-bit

```
-------------- Clean: Debug in example_mic (compiler: Microsoft VC 2017)---------------

Cleaned "example_mic - Debug"

-------------- Build: Debug in example_mic (compiler: Microsoft VC 2017)---------------

cl.exe /nologo   /I"..\..\..\..\C Libraries\gsl-2.4\rng" /I"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.10.25017\include" /I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\ucrt" /I"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.10.25017\atlmfc\include" /I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\shared" /I"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.10.25017\lib\x64" /c main.cpp /Foobj\Debug\Users\lucao\Desktop\example_mic\main.obj
main.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.10.25017\include\xlocale(314): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
..\..\..\..\C Libraries\gsl-2.4\rng\gsl_rng.h(23): fatal error C1083: Cannot open include file: 'gsl/gsl_types.h': No such file or directory
Process terminated with status 2 (0 minute(s), 0 second(s))
0 error(s), 0 warning(s) (0 minute(s), 0 second(s))
```
Why the compiler wants 'gsl/gsl_types.h'? There's a 'gsl_types.h' alright, but not in that directory.

**Comment by BrianGladman** [comment]
If you followed the build instructions for GSL correctly, the file 'gsl/gsl_types.h' will be in the 'gsl' sub-directory within your GSL root directory.   To build an example you need to add this sub-directory to the build properties for the example (this is set in the <Configuration Properties|C++|Additional Include Directories> item in the project's properties (right click on the project in the solution explorer and select properties to access it).

**Comment by lbertolotti** [comment]
https://www.gnu.org/software/gsl/extras/native_win_builds.html
This output was generated by option number 1, do you think I need Cmake?

**Comment by BrianGladman** [comment]
No, you don't need Cmake as the approach used here doesn't depend on it.   If you follow the instructions for building GSL you should be able to build a working GSL library.   When building an application that uses the library you need to tell the application where it can find the GSL header files (i.e in the GSL sub-directory within your GSL root directory) and where it can find the GSL library (i.e for an x64 release build this will be at lib\x64\Release\gsl.lib within your GSL root directory).  You set these in the properties dialogue for your application.

**Comment by lbertolotti** [comment]
>  If you follow the instructions for building GSL you should be able to build a working GSL library
Did you use Windows Power Shell or something else for that?

**Comment by BrianGladman** [comment]
The instructions for building GSL are provided in the file 'gsl.readme.txt' which can be found in the build.vc sub-directory.

**Comment by lbertolotti** [comment]
You mean gsl/README.txt:
"GSL follows the standard GNU installation procedure.  Please consult
the INSTALL file in this distribution for more detailed instructions." ?

**Comment by BrianGladman** [comment]
No, please read what I said above.  The instructions are in the 'gsl.readme.txt' file in the 'build.vc' sub-directory of this GITHUB repository. You have to use GIT to clone this repository in order to to use it.  If you have done this, you should be able to find the instructions on your local machine.

**Comment by BrianGladman** [comment]
Here is a link to the build instructions:

https://github.com/BrianGladman/gsl/blob/master/build.vc/gsl.readme.txt

**Comment by lbertolotti** [comment]
```
-------------- Build: Release x64 in gslhdrs (compiler: Microsoft VC 2017)---------------

link.exe /nologo /subsystem:windows /LIBPATH:"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.10.25017\include" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\ucrt" /LIBPATH:"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.10.25017\atlmfc\include" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\shared" /LIBPATH:"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.10.25017\lib\x64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.15063.0\um\x64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.15063.0\ucrt\x64" /out:gslhdrs.exe  .objs\gslhdrs.obj  /debug 
LIBCMT.lib(exe_winmain.obj) : error LNK2019: unresolved external symbol WinMain referenced in function "int __cdecl __scrt_common_main_seh(void)" (?__scrt_common_main_seh@@YAHXZ)
gslhdrs.exe : fatal error LNK1120: 1 unresolved externals
Process terminated with status 1120 (0 minute(s), 0 second(s))
2 error(s), 0 warning(s) (0 minute(s), 0 second(s))
```

**Comment by BrianGladman** [comment]
This distribution of GSL is designed to be built as a **Windows Desktop** console application.   From your error report it seems that you are trying to build it as a **Universal Windows** application.  When you installed Visual Studio did you ask to add the workload for **Desktop development with C++**?   If not you will need to use the Visual Studio installer to modify your Visual Studio installation to add this workload in order to build GSL.  Alternatively, you could manually modify the code by replacing "int main(void)" with "WinMain()" but there will be no guarantee that the build will work without the need for further modifications.

**Comment by lbertolotti** [comment]
![vs build tools](https://user-images.githubusercontent.com/19675068/28248206-ea156d1a-6a16-11e7-9e16-085256e8234d.png)

**Comment by BrianGladman** [comment]
Thank you for the screenshot - as far as I can tell, you have the necessary components installed.  Can you check under linker properties that the console subsystem is selected - see attached screenshot
![linkprop](https://user-images.githubusercontent.com/400139/28248451-d77858ae-6a3c-11e7-8dd4-2a77f814b2a3.png)

**Comment by lbertolotti** [comment]
I thought that was set by default, yet I had to configure it for a console application. Ok, so now I have gsl/gsl_types.h:
```
-------------- Clean: Debug in example_mic (compiler: Microsoft VC 2017)---------------

Cleaned "example_mic - Debug"

-------------- Build: Debug in example_mic (compiler: Microsoft VC 2017)---------------

cl.exe /nologo /W3 /EHsc  /MDd /Zi /D_DEBUG    /I..\..\..\..\gsl /I"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.10.25017\include" /I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\ucrt" /I"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.10.25017\atlmfc\include" /I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\shared" /I"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.10.25017\lib\x64" /I"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.15063.0\um\x64" /I"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.15063.0\ucrt\x64" /c main.cpp /Foobj\Debug\main.obj
main.cpp
link.exe /nologo /LIBPATH:..\..\..\..\gsl /LIBPATH:"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.10.25017\include" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\ucrt" /LIBPATH:"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.10.25017\atlmfc\include" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\shared" /LIBPATH:"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.10.25017\lib\x64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.15063.0\um\x64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.15063.0\ucrt\x64" /out:bin\Debug\example_mic.exe msvcrtd.lib msvcprtd.lib obj\Debug\main.obj  /debug /DEBUG 
LINK : bin\Debug\example_mic.exe not found or not built by the last incremental link; performing full link
Output file is bin\Debug\example_mic.exe with size 40.50 KB
Process terminated with status 0 (0 minute(s), 0 second(s))
0 error(s), 0 warning(s) (0 minute(s), 0 second(s))
```
Ok, so last question. When should I use the shell command "./configure && make && make install"? This looks like a Linux terminal command, not a Windows PowerShell cmdlet.

**Comment by BrianGladman** [comment]
If you cloned this repository using GIT, **console** would have been set so its not clear why it wasn't.  You don't use configure etc as these are purely for *nix/GCC builds.
