### ISSUE TITLE
Build options: gsllib and cblaslib

### ISSUE THREAD

**Issue by lbertolotti** [BrianGladman/gsl#9]
Should these projects be built as static libraries or console applications?

**Comment by BrianGladman** [comment]
Library builds do not have linker options so your question is not meaningful.  Are you actually using the build files I provide here?   It is hard to see why you are having problems since the build files have the correct settings and yet it appears that you are having to set them yourself.

**Comment by lbertolotti** [comment]
Building gsllib project as a static library:
```
-------------- Clean: Release x64 in gsllib (compiler: Microsoft VC 2017)---------------

Cleaned "gsllib - Release x64"

-------------- Build: Release x64 in gsllib (compiler: Microsoft VC 2017)---------------

"A lot of objs"

eval.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
matrix.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
Output file is gsllib.lib with size 12.50 MB
Process terminated with status 0 (1 minute(s), 28 second(s))
0 error(s), 4 warning(s) (1 minute(s), 28 second(s))
```
But gsl/lib has no library files.

**Comment by BrianGladman** [comment]
Please open a command prompt in the gsl/lib sub-directory and run the command "dir /s *.lib" and report its output.

**Comment by lbertolotti** [comment]
cmd:
```
C:\gsl\lib>dir
 Volume in drive C has no label.
 Volume Serial Number is D64E-D646

 Directory of C:\gsl\lib

16-Jul-17  23:46    <DIR>          .
16-Jul-17  23:46    <DIR>          ..
16-Jul-17  23:46                60 .gitignore
               1 File(s)             60 bytes
               2 Dir(s)  258,300,362,752 bytes free

C:\gsl\lib>dir /s *.lib
 Volume in drive C has no label.
 Volume Serial Number is D64E-D646
File Not Found
```

**Comment by BrianGladman** [comment]
Not c:\gsl\lib but the lib file inside your GSL root directory.

**Comment by lbertolotti** [comment]
That's the only lib subdirectory I have. The build files are in build.vc along with cblaslib, libtest, gslhdrs, etc.

**Comment by BrianGladman** [comment]
If you browse this repository you will see that the root directory (gsl) includes the sub-directories 'dll' and 'lib' 
![capture](https://user-images.githubusercontent.com/400139/28342874-60a10a6e-6c12-11e7-91af-5a4bdb0eb098.PNG)
You have not cloned this repository correctly if you don't have these sub-directories.  This would explain why you are having problems in building gsl.  I suggest you use GIT to clone this repository correctly and try again from scratch.

**Comment by lbertolotti** [comment]
```
PS C:\> git clone https://github.com/BrianGladman/gsl
Cloning into 'gsl'...
remote: Counting objects: 50304, done.
remote: Total 50304 (delta 0), reused 0 (delta 0), pack-reused 50304
Receiving objects: 100% (50304/50304), 18.30 MiB | 550.00 KiB/s, done.
Resolving deltas: 100% (40914/40914), done.
Checking out files: 100% (2726/2726), done.
```
Documents/Visual Studio 2017/Projects is empty

**Comment by BrianGladman** [comment]
If you clone this repository into 'c:\gsl' (as you appear to have done successfully) why on earth would you expect it to be placed into the directory 'documents\visual studio 2017\projects'?   If you want gsl in the directory 'documents\visual studio 2017\projects', simply clone it there, not into 'c:\gsl'.

Or, now that you have the gsl repository in 'c;\gsl', simply copy or move the directory 'c:\gsl' as a whole into the directory 'documents\visual studio 2017\projects'.

The gsl.readme.txt file in the build.vc directory explains  how to build gsl; it also explains where the build process puts the resulting libraries.  Please **read and understand** these instructions as it is a waste of my time and your own in asking questions here when they are fully explained in this document.

**Comment by lbertolotti** [comment]
1. I asked about build options, you didn't answer the question, and told me about linker options
2. Then I ran dir /s *.lib and found nothing
3. Then you told me to look for another sub-directory, which was the same
4. Now you keep repeating the instructions in gsl.readme.txt, which I already know, telling me about the location of some files in subdirectory which are not there
*gsl.lib.sln refers to gsldefs, gslhdrs, gsllib, cblaslib  
*gsl.dll.sln refers to gsldefs, gslhdrs, gsldll, cblasdll
Now I've built gslhdrs as a console application and already got the header files in gsl/gsl.
Building cblaslib and gsllib as static libraries gives me cblaslib.lib and and gsllib.lib, but gsl/lib and gsl/dll are EMPTY. Now building those projects as console applications just gives me fatal error LNK1561 and solves nothing.

**Comment by BrianGladman** [comment]
From what you say, It appears that you can build both gsl.lib and cblas.lib but you don't find the resulting libraries in the correct locations.  I hence suggest that you use the project properties to check the full path to the output  directory.  Here is the result of these dialogues on my system.
![capture](https://user-images.githubusercontent.com/400139/28387437-1390e978-6cc7-11e7-94dc-4d2316640a9a.PNG)  Please show the same set of dialogues on your system.

**Comment by lbertolotti** [comment]
Configuring the output directory pretty much solves it:
![gslib](https://user-images.githubusercontent.com/19675068/28759819-ec9d8998-7577-11e7-9887-7baee512af3b.png)
This is from [Code::Blocks](http://www.codeblocks.org/), an open-source IDE.
```
C:\gsl\lib>dir /s *.lib
 Volume in drive C has no label.
 Volume Serial Number is D64E-D646

 Directory of C:\gsl\lib\x64\debug

30-Jul-17  22:04           604,008 cblaslib.lib
30-Jul-17  22:09        24,143,998 gsllib.lib
               2 File(s)     24,748,006 bytes

 Directory of C:\gsl\lib\x64\release

30-Jul-17  22:05           604,008 cblaslib.lib
30-Jul-17  22:07        13,111,254 gsllib.lib
               2 File(s)     13,715,262 bytes

     Total Files Listed:
               4 File(s)     38,463,268 bytes
               0 Dir(s)  254,486,274,048 bytes free
```

**Comment by BrianGladman** [comment]
The build files for Visual Studio 2017 already configure the output directories so no changes are needed here.
